sudo: false
language: elixir
elixir:
  - 1.9.0
otp_release:
  - 22.0

matrix:
  exclude:
  - otp_release: 22.0
    elixir: 1.6

script:
  - "mix format --check-formatted --dry-run"
  - "MIX_ENV=test mix do deps.get, test"
